"""
Visualization of the three symmetry types generated by the data_generation module.

Produces a 3-column figure (one column per symmetry) with the following rows:
  Row 1 – Input space structure (2-D slice or pair-plot of first 2 features)
  Row 2 – Latent variable vs output  (shows the true invariant)
  Row 3 – Orbit samples  (points that share the same latent value, coloured by y)

Usage
-----
    python -m projects.20260912_Stage1_Prokash.visualization.plot_symmetries
or
    python projects/20260912_Stage1_Prokash/visualization/plot_symmetries.py
"""

import sys
import os

# Make sure the project root and the data_generation folder are importable
_here = os.path.dirname(os.path.abspath(__file__))
_data_gen = os.path.join(_here, "..", "data_generation")
sys.path.insert(0, _here)
sys.path.insert(0, _data_gen)
sys.path.insert(0, os.path.join(_here, "../../.."))

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

from rotational import generate_rotational_data
from translational import generate_translational_data
from scaling import generate_scaling_data


# ---------------------------------------------------------------------------
# Generate data
# ---------------------------------------------------------------------------
N = 800

rot  = generate_rotational_data(n_inputs=2, n_samples=N, seed=0)
tran = generate_translational_data(n_inputs=2, m_orbits=1, n_samples=N, seed=0)
scal = generate_scaling_data(n_inputs=2, m_scaling_vars=1,
                              scaling_exponents=np.array([[1.0, -1.0]]),
                              n_samples=N, seed=0)

datasets = [rot, tran, scal]
titles   = ["Rotational Symmetry", "Translational Symmetry", "Scaling Symmetry"]
colors   = ["#4C72B0", "#DD8452", "#55A868"]


# ---------------------------------------------------------------------------
# Helper: compute the 1-D latent for each dataset
# ---------------------------------------------------------------------------
def latent_rotational(data):
    X, c = data["X"], data["coefficients"]
    return (X ** 2) @ c  # r = sum a_i x_i^2

def latent_translational(data):
    X, W = data["X"], data["orbit_directions"]
    return (X @ W.T).ravel()  # z = W x

def latent_scaling(data):
    # log(pi) = E @ log(X).T
    X = data["X"]
    E = data["scaling_vectors"]
    return (np.log(X) @ E.T).ravel()

latent_fns = [latent_rotational, latent_translational, latent_scaling]
latent_labels = [r"$r = \sum a_i x_i^2$",
                 r"$z = \mathbf{w} \cdot \mathbf{x}$",
                 r"$\log\pi = \mathbf{e} \cdot \log\mathbf{x}$"]
input_labels = [("$x_1$", "$x_2$"),
                ("$x_1$", "$x_2$"),
                (r"$\log x_1$", r"$\log x_2$")]


# ---------------------------------------------------------------------------
# Build figure:  3 rows × 3 cols
# ---------------------------------------------------------------------------
fig = plt.figure(figsize=(15, 12))
fig.suptitle("Symmetry Data Visualization", fontsize=16, fontweight="bold", y=0.98)

gs = gridspec.GridSpec(3, 3, figure=fig, hspace=0.45, wspace=0.38)

row_titles = [
    "Input space  (coloured by $y$)",
    "Latent variable vs output",
    "Orbit samples  (same latent, coloured by $y$)",
]

for col, (data, title, color, latent_fn, ll, il) in enumerate(
        zip(datasets, titles, colors, latent_fns, latent_labels, input_labels)):

    X   = data["X"]
    y   = data["y"]
    lat = latent_fn(data)

    # ------------------------------------------------------------------
    # Row 0 – Scatter of x1 vs x2 coloured by y
    # ------------------------------------------------------------------
    ax0 = fig.add_subplot(gs[0, col])
    x_plot = np.log(X) if data["symmetry_type"] == "scaling" else X
    sc = ax0.scatter(x_plot[:, 0], x_plot[:, 1], c=y, cmap="RdYlBu_r",
                     s=12, alpha=0.7, linewidths=0)
    fig.colorbar(sc, ax=ax0, fraction=0.046, pad=0.04, label="$y$")
    ax0.set_xlabel(il[0], fontsize=10)
    ax0.set_ylabel(il[1], fontsize=10)
    ax0.set_title(title, fontsize=11, fontweight="bold")
    if col == 0:
        ax0.annotate(row_titles[0], xy=(-0.35, 0.5), xycoords="axes fraction",
                     rotation=90, va="center", fontsize=9, color="gray")

    # ------------------------------------------------------------------
    # Row 1 – Latent vs y  (should collapse to a 1-D curve)
    # ------------------------------------------------------------------
    ax1 = fig.add_subplot(gs[1, col])
    sort_idx = np.argsort(lat)
    ax1.scatter(lat, y, c=color, s=8, alpha=0.4, linewidths=0)
    # overlay the clean curve
    ax1.plot(lat[sort_idx], data["y_clean"][sort_idx],
             color="black", lw=1.5, label="$y_{clean}$", zorder=5)
    ax1.set_xlabel(ll, fontsize=10)
    ax1.set_ylabel("$y$", fontsize=10)
    ax1.set_title("Latent → Output", fontsize=10)
    ax1.legend(fontsize=8)
    if col == 0:
        ax1.annotate(row_titles[1], xy=(-0.35, 0.5), xycoords="axes fraction",
                     rotation=90, va="center", fontsize=9, color="gray")

    # ------------------------------------------------------------------
    # Row 2 – Orbit samples: fix latent ≈ target, vary null direction
    # ------------------------------------------------------------------
    ax2 = fig.add_subplot(gs[2, col])

    sym = data["symmetry_type"]

    if sym == "rotational":
        # Orbit: all points with r ≈ r0 lie on an ellipse x1²+x2²= r0
        r0 = np.median(lat)
        theta = np.linspace(0, 2 * np.pi, 400)
        c0 = data["coefficients"]
        x1_orb = np.sqrt(r0 / c0[0]) * np.cos(theta)
        x2_orb = np.sqrt(r0 / c0[1]) * np.sin(theta)
        y_orb  = np.sin(r0) + 0.1 * r0
        ax2.plot(x1_orb, x2_orb, color="black", lw=1.5, label=f"orbit $r={r0:.2f}$")
        sc2 = ax2.scatter(X[:, 0], X[:, 1], c=y, cmap="RdYlBu_r",
                          s=10, alpha=0.5, linewidths=0)
        fig.colorbar(sc2, ax=ax2, fraction=0.046, pad=0.04, label="$y$")
        ax2.set_xlabel("$x_1$", fontsize=10)
        ax2.set_ylabel("$x_2$", fontsize=10)

    elif sym == "translational":
        # Orbit: fix z = w·x, vary x along null direction
        W   = data["orbit_directions"]          # (1, 2)
        orth = data["orthogonal_directions"]    # (2, 1)
        z0  = np.median(lat)
        # anchor point closest to origin on the constraint line
        anchor = W.ravel() * z0 / np.dot(W.ravel(), W.ravel())
        t = np.linspace(-4, 4, 400)
        orb_x1 = anchor[0] + t * orth[0, 0]
        orb_x2 = anchor[1] + t * orth[1, 0]
        y_orb = data["y_clean"][np.argmin(np.abs(lat - z0))]
        ax2.plot(orb_x1, orb_x2, color="black", lw=1.5,
                 label=f"orbit $z={z0:.2f}$")
        sc2 = ax2.scatter(X[:, 0], X[:, 1], c=y, cmap="RdYlBu_r",
                          s=10, alpha=0.5, linewidths=0)
        fig.colorbar(sc2, ax=ax2, fraction=0.046, pad=0.04, label="$y$")
        ax2.set_xlim(-4, 4); ax2.set_ylim(-4, 4)
        ax2.set_xlabel("$x_1$", fontsize=10)
        ax2.set_ylabel("$x_2$", fontsize=10)

    else:  # scaling
        # Orbit in log-space: fix log(pi) = e·log(x), vary along null
        E    = data["scaling_vectors"]          # (1, 2)
        orth = data["scaling_orbit_directions"] # (2, 1)
        logX = np.log(X)
        lp0  = np.median(lat)
        anchor_log = E.ravel() * lp0 / np.dot(E.ravel(), E.ravel())
        t = np.linspace(-2, 2, 400)
        orb_lx1 = anchor_log[0] + t * orth[0, 0]
        orb_lx2 = anchor_log[1] + t * orth[1, 0]
        ax2.plot(orb_lx1, orb_lx2, color="black", lw=1.5,
                 label=rf"orbit $\log\pi={lp0:.2f}$")
        sc2 = ax2.scatter(logX[:, 0], logX[:, 1], c=y, cmap="RdYlBu_r",
                          s=10, alpha=0.5, linewidths=0)
        fig.colorbar(sc2, ax=ax2, fraction=0.046, pad=0.04, label="$y$")
        ax2.set_xlabel(r"$\log x_1$", fontsize=10)
        ax2.set_ylabel(r"$\log x_2$", fontsize=10)

    ax2.set_title("Symmetry Orbit", fontsize=10)
    ax2.legend(fontsize=8)
    if col == 0:
        ax2.annotate(row_titles[2], xy=(-0.35, 0.5), xycoords="axes fraction",
                     rotation=90, va="center", fontsize=9, color="gray")

# ---------------------------------------------------------------------------
# Save
# ---------------------------------------------------------------------------
out_dir = os.path.dirname(os.path.abspath(__file__))
out_path = os.path.join(out_dir, "symmetry_plots.png")
fig.savefig(out_path, dpi=150, bbox_inches="tight")
print(f"Saved → {out_path}")
plt.close(fig)
